//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class rental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rental()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string car { get; set; }
        public string c_name { get; set; }
        public string from_date { get; set; }
        public string return_date { get; set; }
        public string total { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Car Car1 { get; set; }
    }
}
